version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: project
    command: python blog_project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/django_db

volumes:
  db_data:
